In [41]:
import pandas as pd

In [42]:
df = pd.read_csv('/Users/aaliyahgritly/Downloads/Bebo study items/(P3) E-commerce project/online_retail_II.csv')

df.head()

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085.0,United Kingdom
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085.0,United Kingdom
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085.0,United Kingdom

In [43]:
df.shape # 1,067,371 rows and 8 columns

(1067371, 8)

In [44]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1067371 entries, 0 to 1067370
Data columns (total 8 columns):
 #   Column       Non-Null Count    Dtype
---  ------       --------------    -----
 0   Invoice      1067371 non-null  object
 1   StockCode    1067371 non-null  object
 2   Description  1062989 non-null  object
 3   Quantity     1067371 non-null  int64
 4   InvoiceDate  1067371 non-null  object
 5   Price        1067371 non-null  float64
 6   Customer ID  824364 non-null   float64
 7   Country      1067371 non-null  object
dtypes: float64(2), int64(1), object(5)
memory usage: 65.1+ MB

In [45]:
df['Price'].sum() #total revenue

np.float64(4962621.628)

In [46]:
df.groupby('Country')['Customer ID'].nunique() # Count of unique invoices per country

Country
Australia                 15
Austria                   13
Bahrain                    2
Belgium                   29
Bermuda                    0
Brazil                     2
Canada                     5
Channel Islands           14
Cyprus                    11
Czech Republic             1
Denmark                   12
EIRE                       5
European Community         1
Finland                   15
France                    95
Germany                  107
Greece                     5
Hong Kong                  0
Iceland                    1
Israel                     4
Italy                     17
Japan                     10
Korea                      2
Lebanon                    1
Lithuania                  1
Malta                      2
Netherlands               23
Nigeria                    1
Norway                    13
Poland                     6
Portugal                  24
RSA                        2
Saudi Arabia               1
Singapore                  1
Spain                     41
Sweden                    19
Switzerland               22
Thailand                   1
USA                        9
United Arab Emirates       4
United Kingdom          5410
Unspecified                7
West Indies                1
Name: Customer ID, dtype: int64

In [47]:
df['Description'].nunique()

5698

In [48]:
df.isnull().sum() # Check for missing values

Invoice             0
StockCode           0
Description      4382
Quantity            0
InvoiceDate         0
Price               0
Customer ID    243007
Country             0
dtype: int64

# Find missing rows

In [49]:
# Count unique entries in 'Customer ID' column
df['Customer ID'].nunique()
print(f"There are {df['Customer ID'].nunique()} unique customer IDs.")

df['Customer ID'].isnull().sum() # Check how many rows in Customer ID are missing
print(f"There are {df['Customer ID'].isnull().sum()} missing rows customer IDs.")

There are 5942 unique customer IDs.
There are 243007 missing rows customer IDs.

In [50]:
df = df.dropna(subset=["Customer ID"]) # Drop rows with missing Customer ID

In [51]:
df.duplicated().sum() # Check for duplicate rows

np.int64(26479)

In [ ]:
# Find how many rows in Customer ID are missing after we dropped them above
df['Customer ID'].isnull().sum()

np.int64(0)

# Remove negative or 0 quantities and prices

In [53]:
df = df[(df["Quantity"] > 0) & (df["Price"] > 0)]

In [54]:
df.isna().sum() # No more missing values

Invoice        0
StockCode      0
Description    0
Quantity       0
InvoiceDate    0
Price          0
Customer ID    0
Country        0
dtype: int64

# Fix the date format

In [59]:
# Check data type of InvoiceDate column
print(df['InvoiceDate'].dtype)

object

In [60]:
df["InvoiceDate"] = pd.to_datetime(df["InvoiceDate"])
print(f"The new data type for InvoiceDate is {df['InvoiceDate'].dtype}.")

The new data type for InvoiceDate is datetime64[ns].

In [65]:
df['Customer ID'].isnull().sum()

np.int64(0)

# Remove duplicates
Exact duplicate rows were identified and removed to prevent inflated revenue, order counts, and customer activity metrics. These duplicates represent data entry or system replication errors rather than legitimate transactions.

In [67]:
df.duplicated().sum() 
print(f"There are {df.duplicated().sum()} duplicate rows remaining in the dataset.")

There are 26124 duplicate rows remaining in the dataset.

In [68]:
df.drop_duplicates(inplace=True) # Drop duplicate rows

In [69]:
print(f"There are {df.duplicated().sum()} duplicate rows remaining in the dataset.")

There are 0 duplicate rows remaining in the dataset.

In [70]:
df.head()

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085.0,United Kingdom
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085.0,United Kingdom
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085.0,United Kingdom

In [71]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 779425 entries, 0 to 1067370
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   Invoice      779425 non-null  object
 1   StockCode    779425 non-null  object
 2   Description  779425 non-null  object
 3   Quantity     779425 non-null  int64
 4   InvoiceDate  779425 non-null  datetime64[ns]
 5   Price        779425 non-null  float64
 6   Customer ID  779425 non-null  float64
 7   Country      779425 non-null  object
dtypes: datetime64[ns](1), float64(2), int64(1), object(4)
memory usage: 53.5+ MB

# Standardize the column names

In [74]:
df.columns = df.columns.str.lower().str.replace(' ', '_') # Standardize column names

In [75]:
df.columns

Index(['invoice', 'stockcode', 'description', 'quantity', 'invoicedate',
       'price', 'customer_id', 'country'],
      dtype='object')

In [ ]:
(df["quantity"] <= 0).sum(), (df["price"] <= 0).sum() # Check for non-positive values in Quantity and Price columns

(np.int64(0), np.int64(0))

# Convert the cleaned version to a csv

In [89]:
df.to_csv('cleaned_online_retail_II.csv', index=False)